package com.example.demo.entity;

import com.example.demo.enums.OrderStatus;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * ╔═══════════════════════════════════════════════════════════════╗
 * ║  Order Entity                                                 ║
 * ╠═══════════════════════════════════════════════════════════════╣
 * ║  WHY IT EXISTS:                                               ║
 * ║  Represents a customer order. Created when a user "checks     ║
 * ║  out" their cart. Contains the snapshot of items at the time   ║
 * ║  of purchase (via OrderItems) so prices are locked in.        ║
 * ║                                                               ║
 * ║  HOW IT WORKS:                                                ║
 * ║  - orderNumber: unique, human-readable identifier (e.g.,     ║
 * ║    "ORD-20260615-ABC123") generated by the service            ║
 * ║  - ManyToOne with User — a user can have many orders          ║
 * ║  - OneToMany with OrderItem — an order has many line items    ║
 * ║  - OrderStatus enum tracks the lifecycle (FSM)                ║
 * ║  - totalAmount: sum of all OrderItem subtotals                ║
 * ║                                                               ║
 * ║  DESIGN PATTERNS:                                             ║
 * ║  - Aggregate Root (Order + OrderItems form an aggregate)      ║
 * ║  - State Machine (OrderStatus transitions)                    ║
 * ║  - Factory Pattern (order number generation)                  ║
 * ╚═══════════════════════════════════════════════════════════════╝
 */
@Entity
@Table(
        name = "orders",
        indexes = {
                @Index(name = "idx_order_user", columnList = "user_id"),
                @Index(name = "idx_order_status", columnList = "status")
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Order {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Human-readable order number like "ORD-20260615-A1B2C3".
     * Generated by OrderService using a Factory pattern.
     */
    @Column(nullable = false, unique = true)
    private String orderNumber;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @Column(nullable = false)
    private Double totalAmount;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private OrderStatus status;

    /**
     * Line items in this order.
     * CascadeType.ALL: when we save the Order, JPA also saves all OrderItems.
     * orphanRemoval: if an item is removed from the list, delete it from DB.
     */
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<OrderItem> items = new ArrayList<>();

    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
